version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - dupl
    - gosec
    - revive
    - copyloopvar
    - nolintlint
  
formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    enable-all-rules: true
    rules:
      # Disable some overly strict rules
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      # Disable unhandled-error for now as it's too strict
      - name: unhandled-error
        disabled: true
      # Disable deep-exit as it's too strict for CLI entry points
      - name: deep-exit
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  sort-results: true
