version: '3'

vars:
  BINARY_NAME: cliutil
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  LDFLAGS: -ldflags "-X github.com/obstreperous-ai/bug-free-octo-succotash/internal/version.Version={{.VERSION}} -X github.com/obstreperous-ai/bug-free-octo-succotash/internal/version.BuildDate={{.BUILD_DATE}} -X github.com/obstreperous-ai/bug-free-octo-succotash/internal/version.GitCommit={{.GIT_COMMIT}}"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build:
    desc: Build the application
    cmds:
      - go build {{.LDFLAGS}} -o {{.BINARY_NAME}} .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"

  install:
    desc: Install the application to $GOPATH/bin
    cmds:
      - go install {{.LDFLAGS}} .

  test:
    desc: Run tests
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.out coverage.html
      - go clean

  run:
    desc: Run the application
    cmds:
      - go run {{.LDFLAGS}} . {{.CLI_ARGS}}

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  ci:
    desc: Run CI checks
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test
      - task: build
